### ISSUE TITLE
Markdown input rendered as link

### ISSUE THREAD

**Issue by johsi-k** [fabbballin/markdown-it-vuepress-code-snippet-enhanced#1]
Hi! I followed the installation/setup instructions, with usage `@[code](@/docs/.vuepress/path/to/file.vue)` but I'm still seeing the markdown input rendered as a link instead of a code snippet. Is there something I'm missing?

**Comment by fabioaanthony** [comment]
You need to setup the config.

In Vuepress's `config.js` add the following:

```
markdown: {
    config: md => {
        md.use(require('markdown-it-vuepress-code-snippet-enhanced'))
    }
}
```

**Comment by johsi-k** [comment]
I've done that as well, as per the setup instructions.

**Comment by fabioaanthony** [comment]
If you'd like to share your code, I can help you debug the issue. Otherwise I don't have any other hints. The plugin is fairly straightforward. The only other thing I can think of is that you have some spacing issue. Be sure to remove any whitespace from the start of this line.
![image](https://user-images.githubusercontent.com/1669470/56543113-81b4d380-653e-11e9-9d5a-7f6fa4e6941c.png)

**Comment by cloydlau** [comment]
Running into the same problem, and I'm sure there's no whitespace.

**Comment by cloydlau** [comment]
I figured it out, it should be
```js
  markdown: {
    plugins: ['markdown-it-vuepress-code-snippet-enhanced'],
  },
```
instead of
```js
  markdown: {
    config: md => {
      md.use(require('markdown-it-vuepress-code-snippet-enhanced'))
    }
  },
```

**Comment by cloydlau** [comment]
And one more thing, it's *.md files I'm importing, which is been rendered as plain text. How can I make it render properly?
